#*****************************************************#
# download scenedetector by:                          #
# pip install --upgrade scenedetect[opencv]           #
# scenedetector from: https://www.scenedetect.com/    #
#*****************************************************#

from scenedetect import detect, AdaptiveDetector, split_video_ffmpeg

scene_list = detect('Replace/me/with/the/path/to/the/original/video/file.mp4', AdaptiveDetector())
split_video_ffmpeg('Replace/me/with/the/path/to/the/original/video/file.mp4', scene_list, 
                   output_dir = "Replace/me/with/the/path/to/the/output/folder")

# There are already the sample results in "video_segmentation/output" generated by the video "video_segmentation/videos/test.mp4"